### ISSUE TITLE
Changes to node_settings.py

### ISSUE THREAD

**Issue by BrendanParmer** [BrendanParmer/NodeToPython#108]
- [x] [Nodes now maintain a minimum and maximum version too](https://github.com/BrendanParmer/NodeToPython-Dev-Tools/issues/7)
- [x] [Move `ST` enum to `node_settings.py`](https://github.com/BrendanParmer/NodeToPython-Dev-Tools/issues/9)
- [x] [Move `NTPNodeSetting` class definition to `node_settings.py`](https://github.com/BrendanParmer/NodeToPython-Dev-Tools/issues/10)

**Comment by BrendanParmer** [comment]
Resolved with https://github.com/BrendanParmer/NodeToPython/pull/117
